export const APP_AUTH_TOKEN_CREATE = "APP_AUTH_TOKEN_CREATE";
export const APP_AUTH_TOKEN_CREATE_SUCCESS = "APP_AUTH_TOKEN_CREATE_SUCCESS";
export const APP_AUTH_TOKEN_CREATE_ERROR = "APP_AUTH_TOKEN_CREATE_ERROR";

export const APP_AUTH_TOKEN_DELETE = "APP_AUTH_TOKEN_DELETE";
export const APP_AUTH_TOKEN_DELETE_SUCCESS = "APP_AUTH_TOKEN_DELETE_SUCCESS";
export const APP_AUTH_TOKEN_DELETE_ERROR = "APP_AUTH_TOKEN_DELETE_ERROR";


export const APP_AUTH_TOKEN_UPDATE = "APP_AUTH_TOKEN_UPDATE";
export const APP_AUTH_TOKEN_UPDATE_SUCCESS = "APP_AUTH_TOKEN_UPDATE_SUCCESS";
export const APP_AUTH_TOKEN_UPDATE_ERROR = "APP_AUTH_TOKEN_UPDATE_ERROR";

export const APP_AUTH_RESTORE_DATA_FROM_STORAGE = "APP_AUTH_RESTORE_DATA_FROM_STORAGE";

export const APP_AUTH_CONFIG_FETCH = "APP_AUTH_CONFIG_FETCH";
export const APP_AUTH_CONFIG_FETCH_SUCCESS = "APP_AUTH_CONFIG_FETCH_SUCCESS";
export const APP_AUTH_CONFIG_FETCH_ERROR = "APP_AUTH_CONFIG_FETCH_ERROR";