export const Config = {
	AMBIENTE: process.env.REACT_APP_ENVIRONTMENT || "nonprod",
	URL_ENDPOINT_AUTH: process.env.REACT_APP_URL_ENDPOINT_AUTH || "",
	URL_ENDPOINT_USER_MANAGEMENT: process.env.URL_ENDPOINT_USER_MANAGEMENT || "",
	URL_ENDPOINT_PASSWORD_RECOVERY: process.env.REACT_APP_URL_ENDPOINT_LOGIN || "",
	URL_ENDPOINT_UTILS: process.env.REACT_APP_URL_ENDPOINT_UTILS || "",
	URL_ENDPOINT_COMMISSIONS: process.env.REACT_APP_URL_ENDPOINT_COMMISSIONS || "",
	URL_ENDPOINT_PAYROLLS: process.env.REACT_APP_URL_ENDPOINT_PAYROLLS || "",
	URL_ENDPOINT_REQUESTS: process.env.REACT_APP_URL_ENDPOINT_REQUESTS || "",
	//secund conexion websocket true
	URL_ENDPOINT_REQUESTS_PORFOLIO: process.env.REACT_APP_URL_ENDPOINT_PORTFOLIO || "",
	URL_ENDPOINT_WEBSOCKET: process.env.REACT_APP_URL_ENDPOINT_WEBSOCKET || "",
	URL_ENDPOINT_WEBSOCKET_PORTFOLIO: process.env.REACT_APP_URL_ENDPOINT_WEBSOCKET_PORTFOLIO || "",
	URL_PORTFOLIO_PAYMENT_GATEWAY: process.env.REACT_APP_URL_PORTFOLIO_PAYMENT_GATEWAY || "",
	URL_ENDPOINT_PLANILLAS: process.env.REACT_APP_URL_COMMISION_ERRORPLANILLA || "",
	URL_PAYMENT_GATEWAY:
		"https://aplicaciones.libertyseguros.co/caja_external/faces/start?_adf_ctrl-state=14qg6cphfh_3&_adf.ctrl-state=15yb8oljzm_3",
	URL_ENDPOINT_OVERCOMMISSIONS: process.env.REACT_APP_URL_ENDPOINT_OVERCOMMISSIONS || "",
	URL_ENDPOINT_OVERCOMMISSIONSTABLE: process.env.REACT_APP_URL_ENDPOINT_OVERCOMMISSIONSTABLE || "",
	URL_ENDPOINT_OVERCOMMISSIONSHISTORY: process.env.REACT_APP_URL_ENDPOINT_OVERCOMMISSIONSHISTORY || "",
	SBU_AUTOS: process.env.REACT_APP_SBU_AUTOS || "[]",
	URL_ENDPOINT_WALLET: process.env.REACT_APP_URL_ENDPOINT_WALLET || "",
	GTM_ID: process.env.REACT_APP_GTM_ID || "",
	URL_ATTACHMENTS: process.env.REACT_APP_URL_ATTACHMENTS || "",
	URL_SUPPORT: process.env.REACT_APP_URL_SUPPORT || "",
	URL_ENDPOINT_REQUESTS_SARLAFT_ORCHESTRATOR: process.env.REACT_APP_URL_ENDPOINT_REQUESTS_SARLAFT_ORCHESTRATOR || "",
	//Funded portfolio
	URL_FUNDED_PORTFOLIO: process.env.REACT_APP_URL_FUNDED_PORTFOLIO || "",
	//chatbot
	URL_CHATBOT_SALESFORCE: process.env.REACT_APP_URL_CHATBOT_SALESFORCE || "",
	URL_CHATBOT_ENCUESTAS: process.env.REACT_APP_URL_CHATBOT_ENCUESTAS || "",
	URL_CHATBOT_AGENT_CONTENT: process.env.REACT_APP_URL_CHATBOT_AGENT_CONTENT || "",
	URL_CHATBOT_AGENT: process.env.REACT_APP_URL_CHATBOT_AGENT || "",
	URL_CHATBOT_SRC: process.env.REACT_APP_URL_CHATBOT_SRC || "",
	URL_RECORD_TYPE: process.env.REACT_APP_URL_RECORD_TYPE || "",
	URL_ENDPOINT_PORTFOLIO_REPORTS: process.env.REACT_APP_URL_ENDPOINT_PORTFOLIO_REPORTS || "",
	URL_ENDPOINT_PDF_CERTIFICATIONS: process.env.REACT_APP_URL_ENDPOINT_CERTIFICATIONS || "",
	//cognito config
	COG_IDENTITY_POOL_ID: process.env.REACT_APP_COG_IDENTITY_POOL_ID || "",
	AWS_SECRET_MANAGER_NAME: process.env.REACT_APP_SECRET_MANAGER_NAME || "",
	//url modulo login
	URL_ENDPOINT_LOGIN: process.env.REACT_APP_URL_ENDPOINT_LOGIN || "",
	URL_ENDPOINT_ADMIN_USER: process.env.REACT_APP_URL_ENDPOINT_ADMIN_USER || "",
	//lambda report Pending Portfolio
	NAME_LAMBDA_INFO_PENDING_REPORT: process.env.REACT_APP_NAME_LAMBDA_INFO_PENDING_REPORT || "",
	// REFERS
	URL_GET_256_REFER: process.env.REACT_APP_URL_ENDPOINT_GET_256_REFER || "",
	URL_GET_128_REFER: process.env.REACT_APP_URL_ENDPOINT_GET_128_REFER || "",
	PYME: {
		REDIRECT_URL: process.env.REACT_APP_URL_ENDPOINT_PYME_REQUEST || "",
	},
	BPM: {
		REDIRECT_URL: process.env.REACT_APP_URL_ENDPOINT_BPM_REQUEST || "",
	},
	PRODUCTION: {
		REDIRECT_URL: process.env.REACT_APP_URL_ENDPOINT_PROD_RENOV_REQUESTS || "",
	},
	RENOVATIONS: {
		REDIRECT_URL: process.env.REACT_APP_URL_ENDPOINT_PROD_RENOV_REQUESTS || "",
	},
	SINISTER: {
		REDIRECT_URL: process.env.REACT_APP_URL_ENDPOINT_SINISTER_REQUEST || "",
	},
	HOME: {
		REDIRECT_URL: process.env.REACT_APP_URL_ENDPOINT_HOME_REQUEST || "",
	},
	CARS_EMMIT: {
		REDIRECT_URL: process.env.REACT_APP_URL_ENDPOINT_CARS_V3_REQUEST || "",
	},
	CARS_MANAGEMENT: {
		REDIRECT_URL: process.env.REACT_APP_URL_ENDPOINT_CARS_V4_REQUEST || "",
	},
	COLECTIVE_CARS: {
		REDIRECT_URL: process.env.REACT_APP_URL_ENDPOINT_COLECTIVE_CARS_REQUEST || "",
	},
	IAXIS: {
		REDIRECT_URL: process.env.REACT_APP_URL_ENDPOINT_IAXIS_REQUEST || "",
	},
	POLICY_MNGMNT: {
		REDIRECT_URL: process.env.REACT_APP_URL_ENDPOINT_POLICY_MNGMNT_REQUEST || "",
	},
	SASIC: {
		REDIRECT_URL: process.env.REACT_APP_URL_ENDPOINT_SASIC_REQUEST || "",
	},
	URL_ENDPOINT_SHORTCUTS_GET: process.env.REACT_APP_URL_ENDPOINT_SHORTCUTS_GET || "",
	URL_ENDPOINT_SHORTCUTS_UPDATE: process.env.REACT_APP_URL_ENDPOINT_SHORTCUTS_UPDATE || "",
	URL_ENDPOINT_RENOVATIONS: process.env.REACT_APP_URL_ENDPOINT_RENOVATIONS || "",
	GOOGLE_RECAPTCHA_TOKEN: process.env.REACT_APP_GOOGLE_RECAPTCHA_TOKEN || "",
	GOOGLE_RECAPTCHA_SITE_KEY: process.env.REACT_APP_GOOGLE_RECAPTCHA_SITE_KEY || "",
	URL_ENDPOINT_MODULES_REQUEST: process.env.REACT_APP_URL_ENDPOINT_MODULES_REQUEST || "",
	URL_ENDPOINT_GET_MODULES_USER_REQUEST: process.env.REACT_APP_URL_ENDPOINT_GET_MODULES_USER_REQUEST || "",
	URL_ENDPOINT_UPDATE_USER_MANAGED_REQUEST: process.env.REACT_APP_URL_ENDPOINT_UPDATE_USER_MANAGED_REQUEST || "",
	URL_ENDPOINT_ADMIN_USER_MAIN_REQUEST: process.env.REACT_APP_URL_ENDPOINT_ADMIN_USER_MAIN_REQUEST || "",
	SECRET_KEYAPP: process.env.REACT_APP_SECRET_KEYAPP || "",
	SECRET_KEYDES: process.env.REACT_APP_SECRET_KEYDES || "",
	APIGEE: {
		ID: process.env.REACT_APP_APIGEE_SECRET_ID || "",
		CLIENT: process.env.REACT_APP_APIGEE_CLIENT_SECRET || "",
		TOKEN_URL: process.env.REACT_APP_APIGEE_GET_TOKEN_URL || "",
		BASE_URL: process.env.REACT_APP_APIGEE_URL_BASE || "",
	},
	URL_ENDPOINT_PUBLICATIONS_GET: process.env.REACT_APP_PUBLICATIONS || "",
	URL_S3_PUBLICATIONS: process.env.REACT_APP_URL_S3_PUBLICATIONS || "",
};
